#!/usr/bin/env bash

case "$1" in
"rb" | "rbp" | "rebuild")
    scripts/rebuildPatches.sh
    ;;
"p" | "patch")
    scripts/build.sh
    ;;
"m" | "up" | "merge")
    scripts/mergeUpstream.sh
    ;;
"b" | "build")
    (
        scripts/build.sh --jar
        cp ./Avalanche-Proxy/bootstrap/target/Avalanche.jar ./
    )
    ;;
"e" | "edit")
    scripts/edit.sh
    ;;
"w" | "wiggle")
    scripts/wigglePatch.py
    ;;
*)
    echo "Avalanche build tool command. This provides a variety of commands to control the Avalanche"
    echo "build. View below for details of the available commands."
    echo ""
    echo "Commands:"
    echo "  * rb, rbp, rebuild | Rebuilds the patches"
    echo "  * p, patch         | Applies all the patches"
    echo "  * m, up, merge     | Utility to aid in merging upstream"
    echo "  * b, build         | Builds the project"
    echo "  * e, edit          | Runs git rebase -i for Waterfall, allowing patches to be easily modified"
    echo "  * w, wiggle        | Helps to apply patches that fail to using default Git."
    ;;
esac
